name: deepsegmentor
channels:
- peterjc123
- menpo
- conda-forge
- defaults
dependencies:
- python=3.5.5
- pytorch=0.4
- scipy
- opencv3
- scikit-image
- scikit-learn
- torchvision=0.2.1
- pip:
  - dominate==2.3.1
  - Pillow==5.0.0
  - numpy==1.14.1
  - visdom==0.1.7
